# Generated by Django 4.1.7 on 2023-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-head']},
        ),
        migrations.AlterField(
            model_name='room',
            name='head',
            field=models.CharField(max_length=80),
        ),
    ]
