# Generated by Django 4.1.7 on 2023-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to source page'),
        ),
    ]
